# Generated by Django 5.0 on 2024-11-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('breakfast', 'breakfast'), ('dinner', 'dinner'), ('supper', 'supper'), ('dessert', 'dessert'), ('drinks', 'drinks'), ('snacks', 'snacks')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('preparetion_time', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='files/images')),
                ('creaetd_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='table', max_length=50)),
                ('number', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('status', models.CharField(choices=[('full', 'full'), ('free', 'free')], default='free', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinemenu.bill')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinemenu.dish')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinemenu.table'),
        ),
    ]
